DROP TABLE IF EXISTS STOPS;

CREATE TABLE STOPS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  stop VARCHAR(250) NOT NULL,
  latitude  VARCHAR(250) DEFAULT NULL,
  longitude VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS ROUTES;

CREATE TABLE ROUTES(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  stops ARRAY[100] NOT NULL
);